### ISSUE TITLE
pkg update pkg: Loading of plugin 'provides' failed:

### ISSUE THREAD

**Issue by Elimelech** [rosorio/pkg-provides#8]
Removed pkg-provides (freeBSD 13.2):
`#pkg remove pkg-provides`

Now pkg doesn't work:
```
root@A9t:/home/luba # pkg update
pkg: Loading of plugin 'provides' failed: Cannot open "/usr/local/lib/pkg//provides.so"
pkg: Plugins cannot be loaded
```
What to do?

**Comment by rosorio** [comment]
You must remove pkg-provides from your pkg configuration by removing "provides" from your
plugin list in /usr/local/etc/pkg.conf

`PLUGINS [ provides ];` will become `PLUGINS [ ];`

**Comment by Elimelech** [comment]
I don't have there lines:

```
# $FreeBSD$
#
# To disable this repository, instead of modifying or removing this file,
# create a /usr/local/etc/pkg/repos/FreeBSD.conf file:
#
#   mkdir -p /usr/local/etc/pkg/repos
#   echo "FreeBSD: { enabled: no }" > /usr/local/etc/pkg/repos/FreeBSD.conf
#

FreeBSD: {
  url: "pkg+http://pkg.FreeBSD.org/${ABI}/quarterly/",
  mirror_type: "srv",
  signature_type: "fingerprints",
  fingerprints: "/usr/share/keys/pkg",
  enabled: no
}
```

**Comment by rosorio** [comment]
It's because you are looking at `/etc/pkg/FreeBSD.conf` not `/usr/local/etc/pkg.conf `.

**Comment by Elimelech** [comment]
no, I have it in /usr/local/etc/repos/FreeBSD.conf

**Comment by rosorio** [comment]
Ok, this is an alternate location for the repos but pkg plugin configuration is in `/usr/local/etc/pkg.conf`
This is the file who has to be updated.

**Comment by Elimelech** [comment]
I don't have such a file in /usr/local/etc/pkg.conf
What should I put in it?

**Comment by rosorio** [comment]
Unless you have a custom install, pkg has a fonfiguration file called pkg.conf
and usually located in /usr/local/etc/pkg.conf (man pkg.conf).

You should modify manually this file in order to activate pkg plugins such as
pkg provides. Otherwise plugins are ignored.

First use `find /usr/local  -name pkg.conf` to see if you didn't miss the file

if you don't know where the file is located you can perform a global grep search
looking for the PKG_DBDIR pattern.

`grep -rIH PKG_DBDIR / 2>/dev/null`

This will take a couple of hours but a the end you will know where the file is.

**Comment by Elimelech** [comment]
Thanks for the help! Found everything.
